#!/bin/bash

# 2>/dev/null = we don't care if it doesn't exist, just don't copy, silence error
cp ~/.tcshrc .tcshrc 2>/dev/null
cp ~/.ssh/config configs/ssh_config 2>/dev/null

# TODO:  is there still any reason to differentiate
# between darwin and linux?  i think my dotfiles work the same on both by now.
# previously, homebrew was a reason since it used to install to `/usr/local`
# but now it is more detectable
# kmo 1 jan 2025 20h32

cp ~/.bash_profile .bashrc 2>/dev/null
cp ~/.zprofile .zprofile 2>/dev/null
