#!/bin/bash

cp .tcshrc ~/.tcshrc


if [[ "$OSTYPE" == "linux-gnu" ]]; then
	echo deploying for linux
	cp .bash_profile ~/.bashrc
	cp .bash_profile_linux ~/.bash_profile
elif [[ "$OSTYPE" == "linux-gnueabihf" ]]; then
	echo "deploying for linux (ARM)"
	cp .bash_profile ~/.bashrc
	cp .bash_profile_linux ~/.bash_profile
elif [[ "$OSTYPE" == "darwin"* ]]; then
	echo deploying for macOS
	cp .bash_profile ~/.bash_profile
else
	echo "not sure how to handle OSTYPE $OSTYPE - preserving bash profiles"
fi

cp git-completion.bash ~/.git-completion.bash
cp git-prompt.sh ~/.git-prompt.sh
cp xcopen-completion.sh ~/.xcopen-completion.sh
cp ssh-completion.sh ~/.ssh-completion.sh
