#!/bin/bash

cp .tcshrc ~/.tcshrc
cp configs/ssh_config ~/.ssh/config

if [[ "$OSTYPE" == "linux-gnu" ]]; then
	echo deploying for linux
	cp .bash_profile ~/.bashrc
	cp .bash_profile_linux ~/.bash_profile
elif [[ "$OSTYPE" == "linux-gnueabihf" ]]; then
	echo "deploying for linux (ARM)"
	cp .bash_profile ~/.bashrc
	cp .bash_profile_linux ~/.bash_profile
elif [[ "$OSTYPE" == "darwin"* ]]; then
	echo deploying for macOS
	cp .bash_profile ~/.bash_profile
	cp scripts/proxy-off.sh ~/.proxy-off.sh
	cp scripts/proxy-on.sh ~/.proxy-on.sh
	cp configs/karabiner.json ~/.config/karabiner/karabiner.json
else
	echo "not sure how to handle OSTYPE $OSTYPE - preserving bash profiles"
fi

cp scripts/git-completion.bash ~/.git-completion.bash
cp scripts/git-prompt.sh ~/.git-prompt.sh
cp scripts/xcopen-completion.sh ~/.xcopen-completion.sh
cp scripts/ssh-completion.sh ~/.ssh-completion.sh

if [ -d "../privatedotfiles" ]; then
  echo "found private dot files."
  echo "deploying ssh aliases."
  ../privatedotfiles/scripts/add_ssh_aliases
  echo "other private dot file utilities should be run manually."
fi
