#!/bin/bash

# check for gnu stow
if ! command -v stow &> /dev/null; then
  echo "Error: Stow is not installed or not available."
  exit 1
fi

# check for brew if on macOS
if [[ $OSTYPE == darwin ]]; then
  if ! command -v brew &> /dev/null; then
    echo "`brew` is not present.  it can be installed with `/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\"`"
  fi
fi

echo "deploying stowed configurations"

echo " - zsh"; stow --verbose=0 zsh

echo "stowed configurations done"

echo "legacy deploys ignored - edit deploy to re-enable as needed"
exit 0

# legacy stuff follows

cp .tcshrc ~/.tcshrc
cp configs/ssh_config ~/.ssh/config


if [[ "$OSTYPE" == "linux-gnu" ]]; then
	echo deploying for linux
	cp .bash_profile ~/.bashrc
	cp .bash_profile_linux ~/.bash_profile
	cp .zprofile ~/.zprofile
elif [[ "$OSTYPE" == "linux-gnueabihf" ]]; then
	echo "deploying for linux (ARM)"
	cp .bash_profile ~/.bashrc
	cp .bash_profile_linux ~/.bash_profile
	cp .zprofile ~/.zprofile
elif [[ "$OSTYPE" == "darwin"* ]]; then
	echo deploying for macOS
	cp .bash_profile ~/.bash_profile
	cp .zprofile ~/.zprofile
	cp configs/karabiner.json ~/.config/karabiner/
else
	echo "not sure how to handle OSTYPE $OSTYPE - preserving bash profiles"
fi

cp scripts/git-completion.bash ~/.git-completion.bash
cp scripts/git-prompt.sh ~/.git-prompt.sh
cp scripts/xcopen-completion.sh ~/.xcopen-completion.sh
cp scripts/ssh-completion.sh ~/.ssh-completion.sh

if [ -d "../privatedotfiles" ]; then
  echo "found private dot files."
  echo "deploying ssh aliases."
  ../privatedotfiles/scripts/add_ssh_aliases
  echo "other private dot file utilities should be run manually."
fi
